name = "affs-backup"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[triggers]
crons = ["0 2 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "akal-future-founders-summit"
database_id = "b37b7c94-2297-4494-8c5b-94dc16ca1b35"

[[r2_buckets]]
binding = "BACKUPS"
bucket_name = "akal-future-founders-summit"
