import { useState, useRef } from 'react';
import { supabase } from '@/lib/supabase';
import type { RegistrationRecord } from '@/types/registration';
import { SUMMIT_FEE } from '@/types/registration';
import RegistrationForm from './RegistrationForm';
import PaymentSuccess from './PaymentSuccess';
import PaymentFailure from './PaymentFailure';
import { Loader2 } from 'lucide-react';

type AppState = 'form' | 'processing' | 'success' | 'failure';
export interface FormDataType { student_name: string; school_name: string; grade: string; city: string; email: string; phone: string; school_board: string; emergency_contact_name: string; emergency_contact_phone: string; accompanied: boolean; consent: boolean; }
const EMPTY_FORM: FormDataType = { student_name: '', school_name: '', grade: '', city: '', email: '', phone: '', school_board: '', emergency_contact_name: '', emergency_contact_phone: '', accompanied: false, consent: false };
const RAZORPAY_KEY_ID = 'YOUR_RAZORPAY_TEST_KEY_ID';
async function sendConfirmationEmail(record: RegistrationRecord) { try { const functionUrl = `${import.meta.env.VITE_SUPABASE_URL}/functions/v1/send-registration-email`; const response = await fetch(functionUrl, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${import.meta.env.VITE_SUPABASE_ANON_KEY}` }, body: JSON.stringify({ registrationId: record.id, studentName: record.student_name, studentEmail: record.email, registrationRef: record.registration_ref }) }); if (!response.ok) console.warn('Email edge function returned non-OK status'); } catch (err) { console.warn('Failed to send confirmation email:', err); } }
export default function Registration() {
  const [appState, setAppState] = useState<AppState>('form'); const [formData, setFormData] = useState<FormDataType>(EMPTY_FORM); const [registration, setRegistration] = useState<RegistrationRecord | null>(null); const [error, setError] = useState(''); const formRef = useRef<HTMLFormElement>(null);
  const handleValidSubmit = async (data: FormDataType) => { setFormData(data); setAppState('processing'); setError(''); try { const { data: inserted, error: insertError } = await supabase.from('registrations').insert({ student_name: data.student_name, school_name: data.school_name, grade: data.grade, city: data.city, email: data.email, phone: data.phone, school_board: data.school_board || null, emergency_contact_name: data.emergency_contact_name || null, emergency_contact_phone: data.emergency_contact_phone || null, accompanied: data.accompanied, consent: data.consent, payment_status: 'pending' }).select().single(); if (insertError || !inserted) throw new Error(insertError?.message || 'Failed to save registration'); const refId = `AFFS-${inserted.id.slice(0, 8).toUpperCase()}`; const { data: updated } = await supabase.from('registrations').update({ registration_ref: refId }).eq('id', inserted.id).select().single(); const record = (updated || inserted) as RegistrationRecord; if (updated) record.registration_ref = refId; await openRazorpayCheckout(record); } catch (err) { console.error('Registration error:', err); setError(err instanceof Error ? err.message : 'Something went wrong. Please try again.'); setAppState('failure'); } };
  const confirmPayment = async (record: RegistrationRecord, paymentId: string) => { const { data: paidRecord } = await supabase.from('registrations').update({ payment_status: 'paid', payment_id: paymentId }).eq('id', record.id).select().single(); const finalRecord = (paidRecord || record) as RegistrationRecord; finalRecord.payment_status = 'paid'; finalRecord.payment_id = paymentId; setRegistration(finalRecord); setAppState('success'); sendConfirmationEmail(finalRecord); };
  const openRazorpayCheckout = (record: RegistrationRecord) => new Promise<void>((resolve) => { const amountInPaise = SUMMIT_FEE * 100; const hasRazorpay = typeof window !== 'undefined' && (window as any).Razorpay; const hasRealKey = RAZORPAY_KEY_ID && RAZORPAY_KEY_ID !== 'YOUR_RAZORPAY_TEST_KEY_ID'; if (!hasRazorpay || !hasRealKey) { simulatePayment(record, resolve); return; } const options = { key: RAZORPAY_KEY_ID, amount: amountInPaise, currency: 'INR', name: 'Akal Future Founders Summit', description: 'Summit Registration — 22–23 October 2026', prefill: { name: record.student_name, email: record.email, contact: record.phone }, theme: { color: '#EA580C' }, handler: async (response: any) => { const paymentId = response.razorpay_payment_id || `pay_${Date.now()}`; await confirmPayment(record, paymentId); resolve(); }, modal: { ondismiss: () => { setRegistration(record); setAppState('failure'); resolve(); } } }; const rzp = new (window as any).Razorpay(options); rzp.on('payment.failed', (resp: any) => { console.error('Payment failed:', resp.error); setRegistration(record); setAppState('failure'); resolve(); }); rzp.open(); });
  const simulatePayment = (record: RegistrationRecord, resolve: () => void) => { const overlay = document.createElement('div'); overlay.style.cssText = 'position:fixed;inset:0;background:rgba(0,0,0,0.5);z-index:9999;display:flex;align-items:center;justify-content:center;padding:20px;'; overlay.innerHTML = `
      <div style="background:#fff;border-radius:16px;max-width:420px;width:100%;padding:32px;box-shadow:0 20px 60px rgba(0,0,0,0.2);font-family:Inter,system-ui,sans-serif;"><div style="text-align:center;margin-bottom:24px;"><div style="width:56px;height:56px;background:#FFF7ED;border-radius:14px;display:flex;align-items:center;justify-content:center;margin:0 auto 16px;"><svg width="28" height="28" viewBox="0 0 24 24" fill="none"><path d="M3 6h18M3 12h18M3 18h18" stroke="#EA580C" stroke-width="2" stroke-linecap="round"/></svg></div><h3 style="font-size:20px;font-weight:700;color:#1A1814;margin:0 0 4px;">Checkout (Demo Mode)</h3><p style="font-size:14px;color:#666;margin:0;">No live payment will be processed.</p></div><div style="background:#FAF7F2;border-radius:12px;padding:16px;margin-bottom:20px;"><div style="display:flex;justify-content:space-between;margin-bottom:8px;"><span style="color:#666;font-size:14px;">Student</span><span style="font-weight:600;color:#1A1814;font-size:14px;">${record.student_name}</span></div><div style="display:flex;justify-content:space-between;"><span style="color:#666;font-size:14px;">Summit</span><span style="font-weight:600;color:#1A1814;font-size:14px;">AFFS 2026</span></div></div><div style="display:flex;gap:12px;"><button id="rzp-cancel" style="flex:1;padding:12px;border:1px solid #FDBA74;border-radius:10px;background:#fff;color:#1A1814;font-weight:600;font-size:14px;cursor:pointer;">Cancel</button><button id="rzp-pay" style="flex:1;padding:12px;border:none;border-radius:10px;background:#EA580C;color:#fff;font-weight:600;font-size:14px;cursor:pointer;">Pay</button></div></div>`; document.body.appendChild(overlay); const cleanup = () => overlay.remove(); overlay.querySelector('#rzp-cancel')?.addEventListener('click', () => { cleanup(); setRegistration(record); setAppState('failure'); resolve(); }); overlay.querySelector('#rzp-pay')?.addEventListener('click', async () => { cleanup(); const paymentId = `pay_demo_${Date.now()}`; await confirmPayment(record, paymentId); resolve(); }); };
  const handleEditRegistration = () => { setAppState('form'); setError(''); }; const handleTryAgain = () => { if (registration) { setAppState('processing'); openRazorpayCheckout(registration); } else setAppState('form'); };
  return (<section id="register" className="py-20 lg:py-28 bg-summit-cream relative overflow-hidden"><div className="absolute top-20 left-0 w-64 h-64 bg-summit-orange-100/40 rounded-full blur-3xl pointer-events-none" /><div className="relative max-w-3xl mx-auto px-5 sm:px-6 lg:px-8"><h2 className="font-display font-bold text-4xl sm:text-5xl text-summit-charcoal leading-tight mb-3 text-balance">Reserve Your{' '}<span className="text-summit-orange-600">Seat</span></h2><p className="text-lg text-summit-charcoal/60 mb-10">Complete the form below to register for the Akal Future Founders Summit.</p>{appState === 'form' && <RegistrationForm ref={formRef} initialData={formData} onSubmit={handleValidSubmit} />}{appState === 'processing' && <div className="bg-white rounded-2xl border border-summit-orange-100 shadow-lg p-12 text-center"><Loader2 className="w-10 h-10 text-summit-orange-600 animate-spin mx-auto mb-4" /><div className="font-display font-bold text-lg text-summit-charcoal mb-1">Processing your registration...</div><div className="text-sm text-summit-charcoal/50">Please don't close this window.</div></div>}{appState === 'success' && registration && <PaymentSuccess registration={registration} />}{appState === 'failure' && <PaymentFailure registration={registration} error={error} onTryAgain={handleTryAgain} onEdit={handleEditRegistration} />}</div></section>);
}
